package py.com.robs.registroempleados.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF315B70)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBDE9FF)
val LightOnPrimaryContainer = Color(0xFF001F2A)
val LightSecondary = Color(0xFF4E616B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD1E5F1)
val LightOnSecondaryContainer = Color(0xFF0A1E27)
val LightTertiary = Color(0xFF5E5A7D)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFE4DFFF)
val LightOnTertiaryContainer = Color(0xFF1B1736)
val LightBackground = Color(0xFFF7F9FC)
val LightOnBackground = Color(0xFF181C1F)
val LightSurface = Color(0xFFF7F9FC)
val LightOnSurface = Color(0xFF181C1F)

val DarkPrimary = Color(0xFF8DCDEA)
val DarkOnPrimary = Color(0xFF003546)
val DarkPrimaryContainer = Color(0xFF0D4D62)
val DarkOnPrimaryContainer = Color(0xFFBDE9FF)
val DarkSecondary = Color(0xFFB5C9D5)
val DarkOnSecondary = Color(0xFF20333C)
val DarkSecondaryContainer = Color(0xFF374A53)
val DarkOnSecondaryContainer = Color(0xFFD1E5F1)
val DarkTertiary = Color(0xFFC8C2EA)
val DarkOnTertiary = Color(0xFF302C4C)
val DarkTertiaryContainer = Color(0xFF464363)
val DarkOnTertiaryContainer = Color(0xFFE4DFFF)
val DarkBackground = Color(0xFF101417)
val DarkOnBackground = Color(0xFFE0E3E6)
val DarkSurface = Color(0xFF101417)
val DarkOnSurface = Color(0xFFE0E3E6)
